import { DetectedRule } from "./importScanner";

export class FormatConverter {
  convertToSynapse(rule: DetectedRule): string {
    switch (rule.ide) {
      case "trae":
        return this.convertFromTrae(rule.content, rule.suggestedName);
      case "cursor":
        return this.convertFromCursor(rule.content, rule.suggestedName);
      case "windsurf":
        return this.convertFromWindsurf(rule.content, rule.suggestedName);
      case "cline":
        return this.convertFromCline(rule.content, rule.suggestedName);
      default:
        return rule.content;
    }
  }

  private convertFromTrae(content: string, fileName: string): string {
    const nameMatch = content.match(/#\s*Rule:\s*(.+)/i);
    const name = nameMatch ? nameMatch[1].trim() : fileName.replace(/\.synapse$/i, "");

    const descMatch = content.match(/#\s*Description:\s*(.+)/i);

    const constraints: string[] = [];
    const skills: string[] = [];
    const lines = content.split("\n");
    for (const line of lines) {
      if (line.includes("# @constraint")) constraints.push(line.replace("# @constraint", "").trim());
      if (line.includes("# @skill")) skills.push(line.replace("# @skill", "").trim());
    }

    const cleanContent = lines
      .filter((l) => !l.startsWith("# Generated by"))
      .filter((l) => !/^#\s*Rule:/i.test(l))
      .filter((l) => !/^#\s*Description:/i.test(l))
      .filter((l) => !/^#\s*Constraints:/i.test(l))
      .filter((l) => !l.includes("# @constraint"))
      .filter((l) => !/^#\s*Skills:/i.test(l))
      .filter((l) => !l.includes("# @skill"))
      .join("\n")
      .trim();

    let result = `# Rule: ${name}\n`;
    if (descMatch) result += `# Description: ${descMatch[1].trim()}\n`;
    result += `\n${cleanContent}\n\n`;

    if (constraints.length > 0) {
      result += `# Constraints:\n`;
      for (const c of constraints) result += `# @constraint ${c}\n`;
      result += `\n`;
    }

    if (skills.length > 0) {
      result += `# Skills:\n`;
      for (const s of skills) result += `# @skill ${s}\n`;
    }

    return result;
  }

  private convertFromCursor(content: string, fileName: string): string {
    const parsed = this.parseFrontmatter(content);
    const title = parsed.frontmatter.title || parsed.frontmatter.name;
    const desc = parsed.frontmatter.description;
    const name = (title || desc || fileName.replace(/\.synapse$/i, "")).trim();

    let result = `# Rule: ${name}\n`;
    if (desc) result += `# Description: ${desc}\n`;
    result += `\n${parsed.body}\n\n`;

    const globsRaw = parsed.frontmatter.globs || parsed.frontmatter.glob || "";
    const globs = globsRaw
      .split(",")
      .map((g) => g.trim())
      .filter(Boolean);

    if (globs.length > 0) {
      result += `# Constraints:\n`;
      for (const g of globs) result += `# @constraint ${g}\n`;
    }

    return result;
  }

  private convertFromWindsurf(content: string, fileName: string): string {
    try {
      const json = JSON.parse(content);
      const name = (json.name || fileName.replace(/\.synapse$/i, "")).toString().trim();

      let result = `# Rule: ${name}\n`;
      if (json.description) result += `# Description: ${String(json.description).trim()}\n`;
      result += `\n${String(json.content || "").trim()}\n`;
      return result;
    } catch {
      return `# Rule: ${fileName.replace(/\.synapse$/i, "")}\n\n${content.trim()}\n`;
    }
  }

  private convertFromCline(content: string, fileName: string): string {
    const match = content.match(/<cline_rule>([\s\S]*?)<\/cline_rule>/i);
    const cleanContent = (match ? match[1] : content).trim();
    return `# Rule: ${fileName.replace(/\.synapse$/i, "")}\n\n${cleanContent}\n`;
  }

  private parseFrontmatter(content: string): { frontmatter: Record<string, string>; body: string } {
    const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
    if (!match) return { frontmatter: {}, body: content.trim() };

    const fmText = match[1];
    const frontmatter: Record<string, string> = {};
    for (const rawLine of fmText.split(/\r?\n/)) {
      const line = rawLine.trim();
      if (!line || line.startsWith("#")) continue;
      const idx = line.indexOf(":");
      if (idx === -1) continue;
      const key = line.slice(0, idx).trim();
      const value = line.slice(idx + 1).trim();
      if (!key) continue;
      frontmatter[key] = value;
    }

    const body = content.replace(match[0], "").trim();
    return { frontmatter, body };
  }
}
