#!/usr/bin/env node

import { WebSocketServer, WebSocket } from "ws";
import * as http from "http";
import * as fs from "fs/promises";
import * as path from "path";
import { randomBytes } from "crypto";

type ClientInfo = {
  id: string;
  ideType: string;
  workspace: string;
  ws: WebSocket;
};

type SynapseRule = {
  id: string;
  name: string;
  description?: string;
  content: string;
  constraints?: string[];
  skills?: string[];
};

function nowId(prefix: string): string {
  return `${prefix}-${Date.now()}-${randomBytes(4).toString("hex")}`;
}

function workspaceDir(raw?: string): string {
  const w = typeof raw === "string" && raw.trim() ? raw.trim() : process.cwd();
  return path.isAbsolute(w) ? w : path.resolve(process.cwd(), w);
}

function isSafeFileName(name: string): boolean {
  if (!name) return false;
  if (name.includes("/") || name.includes("\\") || name.includes("\0")) return false;
  if (name.startsWith(".")) return false;
  if (name.includes("..")) return false;
  return true;
}

function extractRuleName(content: string, fallback: string): string {
  const nameMatch = content.match(/^# Rule:\s*(.+)$/m);
  const name = nameMatch && nameMatch[1] ? nameMatch[1].trim() : "";
  return name || fallback;
}

function extractDescription(content: string): string | undefined {
  const m = content.match(/^# Description:\s*(.+)$/m);
  const v = m && m[1] ? m[1].trim() : "";
  return v || undefined;
}

function extractList(content: string, token: "# @constraint" | "# @skill"): string[] {
  const out: string[] = [];
  for (const line of content.split("\n")) {
    const idx = line.indexOf(token);
    if (idx >= 0) out.push(line.slice(idx + token.length).trim());
  }
  return out;
}

function cleanRuleBody(content: string): string {
  return content
    .split("\n")
    .filter((l) => !l.startsWith("# Rule:"))
    .filter((l) => !l.startsWith("# Description:"))
    .filter((l) => !l.startsWith("# Constraints:"))
    .filter((l) => !l.startsWith("# @constraint"))
    .filter((l) => !l.startsWith("# Skills:"))
    .filter((l) => !l.startsWith("# @skill"))
    .join("\n")
    .trim();
}

function parseSynapseRule(content: string, filePath: string): SynapseRule {
  const id = path.basename(filePath, path.extname(filePath));
  const name = extractRuleName(content, id);
  const description = extractDescription(content);
  const constraints = extractList(content, "# @constraint");
  const skills = extractList(content, "# @skill");
  const body = cleanRuleBody(content);
  return { id, name, description, content: body, constraints, skills };
}

function compileTrae(rule: SynapseRule, minify?: boolean): string {
  const lines: string[] = [];
  lines.push(`# Generated by Synapse from ${rule.name}`);
  lines.push(`# Rule: ${rule.name}`);
  if (rule.description) lines.push(`# Description: ${rule.description}`);
  lines.push("");
  if (rule.constraints && rule.constraints.length) {
    lines.push("# Constraints:");
    for (const c of rule.constraints) lines.push(`# @constraint ${c}`);
    lines.push("");
  }
  lines.push(minify ? rule.content.trim() : rule.content);
  lines.push("");
  if (rule.skills && rule.skills.length) {
    lines.push("# Skills:");
    for (const s of rule.skills) lines.push(`# @skill ${s}`);
  }
  return lines.join("\n");
}

function compileCursor(rule: SynapseRule, minify?: boolean): string {
  const parts: string[] = [];
  parts.push("---");
  parts.push(`description: ${rule.description || rule.name}`);
  const globs = rule.constraints && rule.constraints.length ? rule.constraints.join(", ") : "**/*";
  parts.push(`globs: ${globs}`);
  parts.push("---");
  parts.push("");
  parts.push(minify ? rule.content.trim() : rule.content);
  if (rule.skills && rule.skills.length) {
    parts.push("");
    parts.push("## Skills");
    for (const s of rule.skills) parts.push(`- ${s}`);
  }
  return parts.join("\n");
}

async function listRuleFiles(workspace: string): Promise<string[]> {
  const rulesPath = path.join(workspace, ".synapse", "rules");
  const files = await fs.readdir(rulesPath).catch(() => []);
  return files.filter((f) => String(f).toLowerCase().endsWith(".synapse"));
}

async function readRules(workspace: string): Promise<Array<{ name: string; content: string }>> {
  const rulesPath = path.join(workspace, ".synapse", "rules");
  const files = await listRuleFiles(workspace);
  const rules = await Promise.all(
    files.map(async (file) => ({
      name: file,
      content: await fs.readFile(path.join(rulesPath, file), "utf8"),
    }))
  );
  return rules;
}

async function ensureSynapseFolders(workspace: string): Promise<void> {
  await fs.mkdir(path.join(workspace, ".synapse", "rules"), { recursive: true });
  await fs.mkdir(path.join(workspace, ".synapse", "skills"), { recursive: true });
}

async function runSync(workspace: string, target: string, minify?: boolean): Promise<{ outputs: string[]; skipped: string[] }> {
  const rulesPath = path.join(workspace, ".synapse", "rules");
  const files = await listRuleFiles(workspace);
  if (files.length === 0) return { outputs: [], skipped: [] };

  const outputs: string[] = [];
  const skipped: string[] = [];
  const supportedTargets = ["trae", "cursor"];
  if (target !== "all" && !supportedTargets.includes(target)) {
    throw new Error(`Unsupported target "${target}". Supported: ${supportedTargets.join(", ")}`);
  }
  const targets = target === "all" ? supportedTargets : [target];

  for (const t of targets) {
    const outDir = t === "trae" ? path.join(workspace, ".trae") : path.join(workspace, ".cursor", "rules");
    await fs.mkdir(outDir, { recursive: true });

    for (const file of files) {
      const inputPath = path.join(rulesPath, file);
      const content = await fs.readFile(inputPath, "utf8");
      const rule = parseSynapseRule(content, inputPath);
      const compiled = t === "trae" ? compileTrae(rule, minify) : compileCursor(rule, minify);
      const ext = t === "trae" ? ".trae" : ".mdc";
      const outputPath = path.join(outDir, `${rule.id}${ext}`);
      await fs.writeFile(outputPath, compiled, "utf8");
      outputs.push(outputPath);
    }
  }

  return { outputs, skipped };
}

export class SynapseWS {
  private wss: WebSocketServer;
  private clients: Map<string, ClientInfo> = new Map();
  private httpServer: http.Server;

  constructor(private port: number = 3457) {
    this.httpServer = http.createServer((req, res) => {
      if (req.url === "/health") {
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ status: "ok", clients: this.clients.size }));
        return;
      }

      if (req.url === "/api/sync" && req.method === "POST") {
        let body = "";
        let total = 0;
        let done = false;
        req.on("data", (chunk) => {
          if (done) return;
          const buf = Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk || ""), "utf8");
          total += buf.length;
          if (total > 64 * 1024) {
            done = true;
            res.writeHead(413, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ success: false, error: "Payload too large" }));
            try {
              req.destroy();
            } catch {
              void 0;
            }
            return;
          }
          body += buf.toString("utf8");
        });
        req.on("end", async () => {
          if (done) return;
          try {
            const parsed = JSON.parse(body || "{}");
            const workspace = workspaceDir(parsed.workspace);
            const target = typeof parsed.target === "string" ? parsed.target : "all";
            const minify = !!parsed.minify;
            const result = await runSync(workspace, target, minify);
            res.writeHead(200, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ success: true, result }));
          } catch (e) {
            res.writeHead(500, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ success: false, error: String(e instanceof Error ? e.message : e) }));
          }
        });
        return;
      }

      res.writeHead(404).end();
    });

    this.wss = new WebSocketServer({ server: this.httpServer });
    this.setupWebSocket();
  }

  private setupWebSocket() {
    this.wss.on("connection", (ws: WebSocket, req: http.IncomingMessage) => {
      const url = new URL(req.url || "/", `http://${req.headers.host || "localhost"}`);
      const ideType = url.searchParams.get("ide") || "unknown";
      const workspace = workspaceDir(url.searchParams.get("workspace") || undefined);
      const clientId = nowId(ideType);

      const client: ClientInfo = { id: clientId, ideType, workspace, ws };
      this.clients.set(clientId, client);
      process.stdout.write(`[WS] Connected: ${ideType} (${clientId})\n`);

      ws.send(JSON.stringify({ type: "welcome", clientId }));
      this.broadcast({ type: "clients", count: this.clients.size });

      ws.on("message", async (data: WebSocket.RawData) => {
        try {
          const msg = JSON.parse(data.toString());
          await this.handleMessage(client, msg);
        } catch (e) {
          ws.send(JSON.stringify({ type: "error", error: String(e instanceof Error ? e.message : e) }));
        }
      });

      ws.on("close", () => {
        this.clients.delete(clientId);
        this.broadcast({ type: "clients", count: this.clients.size });
      });
    });
  }

  private async handleMessage(client: ClientInfo, msg: any) {
    switch (msg?.type) {
      case "sync":
        await this.doSync(client, msg);
        break;
      case "get_rules":
        await this.sendRules(client);
        break;
      case "update_rule":
        await this.updateRule(client, msg);
        break;
      case "create_rule":
        await this.createRule(client, msg);
        break;
      default:
        client.ws.send(JSON.stringify({ type: "error", error: `Unknown message type: ${String(msg?.type)}` }));
        break;
    }
  }

  private async doSync(client: ClientInfo, msg: any) {
    const target = typeof msg?.target === "string" ? msg.target : "all";
    const requestId = typeof msg?.requestId !== "undefined" ? msg.requestId : null;
    const minify = !!msg?.minify;

    client.ws.send(JSON.stringify({ type: "sync_started", requestId }));
    try {
      await ensureSynapseFolders(client.workspace);
      const result = await runSync(client.workspace, target, minify);
      client.ws.send(JSON.stringify({ type: "sync_complete", requestId, success: true, result }));
      this.broadcast({ type: "sync_broadcast", source: client.ideType, target }, client.id);
    } catch (e) {
      client.ws.send(JSON.stringify({ type: "sync_error", requestId, error: String(e instanceof Error ? e.message : e) }));
    }
  }

  private async sendRules(client: ClientInfo) {
    const requestId = null;
    try {
      const rules = await readRules(client.workspace);
      client.ws.send(JSON.stringify({ type: "rules_list", requestId, rules, count: rules.length }));
    } catch {
      client.ws.send(JSON.stringify({ type: "rules_list", requestId, rules: [], count: 0 }));
    }
  }

  private async updateRule(client: ClientInfo, msg: any) {
    const ruleName = typeof msg?.ruleName === "string" ? msg.ruleName : "";
    const content = typeof msg?.content === "string" ? msg.content : "";
    if (!isSafeFileName(ruleName)) {
      client.ws.send(JSON.stringify({ type: "error", error: "Invalid ruleName" }));
      return;
    }

    await ensureSynapseFolders(client.workspace);
    const fileName = ruleName.toLowerCase().endsWith(".synapse") ? ruleName : `${ruleName}.synapse`;
    const rulePath = path.join(client.workspace, ".synapse", "rules", fileName);
    await fs.writeFile(rulePath, content, "utf8");
    client.ws.send(JSON.stringify({ type: "rule_updated", ruleName: fileName }));
    this.broadcast({ type: "rule_changed", ruleName: fileName, action: "update" }, client.id);
  }

  private async createRule(client: ClientInfo, msg: any) {
    const ruleName = typeof msg?.ruleName === "string" ? msg.ruleName : "";
    const content = typeof msg?.content === "string" ? msg.content : "";
    if (!isSafeFileName(ruleName)) {
      client.ws.send(JSON.stringify({ type: "error", error: "Invalid ruleName" }));
      return;
    }

    await ensureSynapseFolders(client.workspace);
    const fileName = ruleName.toLowerCase().endsWith(".synapse") ? ruleName : `${ruleName}.synapse`;
    const rulePath = path.join(client.workspace, ".synapse", "rules", fileName);
    const defaultContent = content || `# Rule: ${fileName.replace(/\.synapse$/i, "")}\n# Description: \n\n# Your rule here\n`;
    await fs.writeFile(rulePath, defaultContent, "utf8");
    client.ws.send(JSON.stringify({ type: "rule_created", ruleName: fileName }));
    this.broadcast({ type: "rule_changed", ruleName: fileName, action: "create" }, client.id);
  }

  private broadcast(msg: any, excludeId?: string) {
    const text = JSON.stringify(msg);
    for (const [id, c] of this.clients) {
      if (id === excludeId) continue;
      if (c.ws.readyState === WebSocket.OPEN) c.ws.send(text);
    }
  }

  start() {
    const host = typeof process.env.WS_HOST === "string" && process.env.WS_HOST.trim() ? process.env.WS_HOST.trim() : "127.0.0.1";
    this.httpServer.listen(this.port, host, () => {
      process.stdout.write(`🧠 Synapse WS: ws://${host}:${this.port} | API: http://${host}:${this.port}/api/sync\n`);
    });
  }
}

new SynapseWS(parseInt(process.env.WS_PORT || "3457", 10)).start();
