// NEW: Trae adapter (v1)

import * as path from "path";
import { IDEAdapter, SynapseRule } from "./adapter.interface";

export class TraeAdapter implements IDEAdapter {
  id = "trae-v1";
  name = "Trae";
  version = "1.0.0";
  targetExtension = ".trae";
  targetFolder = ".trae/";

  async compile(rule: SynapseRule, options: { minify?: boolean } = {}): Promise<string> {
    const lines: string[] = [];

    lines.push(`# Generated by Synapse from ${rule.name}`);
    lines.push(`# Rule: ${rule.name}`);
    if (rule.description) {
      lines.push(`# Description: ${rule.description}`);
    }
    lines.push("");

    if (rule.constraints?.length) {
      lines.push("# Constraints:");
      for (const c of rule.constraints) lines.push(`# @constraint ${c}`);
      lines.push("");
    }

    const content = options.minify ? rule.content.trim() : rule.content;
    lines.push(content);
    lines.push("");

    if (rule.skills?.length) {
      lines.push("# Skills:");
      for (const s of rule.skills) lines.push(`# @skill ${s}`);
    }

    return lines.join("\n");
  }

  async parse(content: string, filePath: string): Promise<SynapseRule> {
    const nameMatch = content.match(/# Rule:\s*(.+)/);
    const descMatch = content.match(/# Description:\s*(.+)/);
    const constraints: string[] = [];
    const skills: string[] = [];

    for (const line of content.split("\n")) {
      if (line.includes("# @constraint")) constraints.push(line.replace("# @constraint", "").trim());
      if (line.includes("# @skill")) skills.push(line.replace("# @skill", "").trim());
    }

    const cleanContent = content
      .split("\n")
      .filter((l) => !l.startsWith("# Generated by Synapse"))
      .filter((l) => !l.startsWith("# Rule:"))
      .filter((l) => !l.startsWith("# Description:"))
      .join("\n");

    const now = new Date();
    return {
      id: path.basename(filePath, path.extname(filePath)),
      name: nameMatch?.[1] || "Unnamed",
      description: descMatch?.[1],
      content: cleanContent.trim(),
      constraints,
      skills,
      metadata: {
        createdAt: now,
        updatedAt: now,
        version: 1,
      },
    };
  }

  async validate(compiled: string): Promise<{ valid: boolean; errors?: string[] }> {
    const errors: string[] = [];
    if (!compiled.includes("# Rule:")) errors.push("Missing rule name");
    return { valid: errors.length === 0, errors };
  }

  getInstallInstructions(): string {
    return "Trae automatically reads .trae files from project root.";
  }
}

